/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "study-planner",
  "name": "Exam Planner",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Add a biology exam on the 20th covering cells, genetics and evolution",
      "does": "Adds the exam with its syllabus."
    },
    {
      "say": "I can only study 2 hours on weekdays",
      "does": "Updates your availability and rebuilds the plan."
    },
    {
      "say": "Quiz me on my weakest topic",
      "does": "Opens a practice quiz on the lowest-mastery topic."
    }
  ]
};
